module Language.CCS.Lexer.NoiseReduction
  ( CCS(..)
  , Token(..)
  , StrToken(..)
  , PunctuationType(..)
  , pipeline
  ) where

import Language.CCS.Types.NoiseReduction

import Control.Monad (when)
import Data.Function ((&))
import Language.CCS.Error (ReaderStyle(..), ReaderError(..), ReaderHooks(..))
import Language.CCS.Lexer.Decode (EolType(..))
import Language.CCS.Util (internalError, unused)
import Language.Nanopass (defpass)
import Streaming.Prelude (yield)
import Streaming (Stream, Of(..))

import qualified Language.CCS.Lexer.Cover as L0
import qualified Streaming as S
import qualified Streaming.Prelude as S

[defpass|(from L0:CCS to CCS)|]

_ignore :: ()
_ignore = unused (XlateI, descendTokenI, descendStrTokenI, descendPunctuationTypeI)

xlate :: ReaderHooks m => Xlate m
xlate = Xlate
  { onToken = \case
      L0.Str l open body close -> Just $ do
        body' <- strDeletions body
        pure $ Str l open body' close
      _ -> Nothing
  , onStrToken = const Nothing
  , onPunctuationType = const Nothing
  , onTokenComment = \_ -> internalError "attempt to translate Comment token to next lexing stage"
  , onTokenIllegal = \_ -> internalError "attempt to translate Illegal token to next lexing stage"
  , onStrTokenIllStr = \_ -> internalError "attempt to translate IllStr token to next lexing stage"
  }

xlateTok :: ReaderHooks m => L0.Token -> m Token
xlateTok = descendToken xlate

xlateStr :: ReaderHooks m => L0.StrToken -> m StrToken
xlateStr = descendStrToken xlate

-- | Gets rid of comments, then trailing whitespace.
-- Raises an error on illegal tokens.
-- It also checks that the file has consistent newline sequences, and that it ends in a newline.
-- The caller gets the chance to do something with comments before their removal.
-- Likewise, the caller gets to choose whether to abort or do error recovery on illegal tokens.
pipeline ::
  ( ReaderHooks m )
  => Stream (Of L0.Token) m r
  -> Stream (Of Token) m r
pipeline input
  = input
  & consistentNewlines Nothing
  & endsInNewline
  & simpleDeletions
  & dedupeWs
  & dedupeEol

simpleDeletions ::
  ( ReaderHooks m )
  => Stream (Of L0.Token) m r
  -> Stream (Of Token) m r
simpleDeletions = loop
  where
  loop inp0 = S.effect $ S.next inp0 >>= \case
  -- raise error and delete illegal tokens
    Right (L0.Illegal txt, inp1) -> do
      recoverableError $ IllegalBytesOrChars txt
      pure $ loop inp1
  -- delete and notify about raw trailing whitespace
    Right (L0.Whitespace ws, inp1) -> S.next inp1 >>= \case
      Right (eol@(L0.Eol _ _), inp2) -> do
        styleNote $ TrailingWhitespace ws
        let rest = yield eol >> inp2
        pure $ loop rest
      Right (other, inp2) -> pure $ do
        yield $ Whitespace ws
        let rest = yield other >> inp2
        loop rest
      Left r -> do
        styleNote $ TrailingWhitespace ws
        pure $ pure r
  -- delete comment tokens
    Right (L0.Comment txt, inp1) -> do
      ignore txt
      pure $ loop inp1
  -- base cases
    Right (other, rest) -> do
      other' <- xlateTok other
      pure $ yield other' >> loop rest
    Left r -> pure $ pure r

strDeletions :: ReaderHooks m
  => [L0.StrToken]
  -> m [StrToken]
strDeletions (L0.IllStr err : rest) = do
  recoverableError $ IllegalBytesOrCharsInString err
  strDeletions rest
strDeletions (other : rest) = do
  other' <- xlateStr other
  (other' :) <$> strDeletions rest
strDeletions [] = pure []

dedupeWs ::
  ( Monad m )
  => Stream (Of Token) m r
  -> Stream (Of Token) m r
dedupeWs inp0 = S.effect $ S.next inp0 >>= \case
  Right (ws@(Whitespace _), inp1) -> S.next inp1 >>= \case
-- remove whitespace before whitespace (may have been generated by deletion of illegal tokens)
    Right (ws2@(Whitespace _), rest) -> pure $ do
      dedupeWs $ yield ws2 >> rest
-- remove whitespace before end of line (may be generated by comment deletion)
    Right (nl@(Eol _ _), rest) -> pure $ do
      dedupeWs $ yield nl >> rest
-- remove whitespace before end of file (may be generated by comment deletion)
    Left r -> do
      pure $ pure r
-- leave the rest alone
    Right (other, inp2) -> pure $ do
      yield ws
      let rest = yield other >> inp2
      dedupeWs rest
-- base cases
  Right (other, inp1) ->
    pure $ yield other >> dedupeWs inp1
  Left r -> pure $ pure r

dedupeEol ::
  ( Monad m )
  => Stream (Of Token) m r
  -> Stream (Of Token) m r
dedupeEol = firstLine
  where
  -- remove newlines at the start of the file
  firstLine inp0 = S.effect $ S.next inp0 >>= \case
    Right (Eol _ _, rest) -> pure $ do
      firstLine rest
  -- transfer to the loop otherwise
    Right (other, inp1) -> pure $ do
      let rest = yield other >> inp1
      loop rest
    Left r -> pure $ pure r
  loop inp0 = S.effect $ S.next inp0 >>= \case
    Right (eol@(Eol _ _), inp1) -> S.next inp1 >>= \case
  -- remove newlines before newlines (indicates a blank line after comment, illegal, and trailg ws stripping)
      Right (eol2@(Eol _ _), rest) -> pure $ do
        loop $ yield eol2 >> rest
  -- leave other newlines alone
      Right (other, inp2) -> pure $ do
        yield eol
        let rest = yield other >> inp2
        loop rest
      Left r -> pure $ do
        yield eol
        pure r
  -- base cases
    Right (other, inp1) ->
      pure $ yield other >> loop inp1
    Left r -> pure $ pure r

consistentNewlines ::
  ( ReaderHooks m )
  => Maybe EolType
  -> Stream (Of L0.Token) m r
  -> Stream (Of L0.Token) m r
consistentNewlines Nothing = loop
  where
  loop inp0 = S.effect $ S.next inp0 >>= \case
    Left r -> pure $ pure r
    Right (nl@(L0.Eol _ ty), rest) ->
      pure $ yield nl >> consistentNewlines (Just ty) rest
    Right (other, rest) -> pure $ yield other >> loop rest
consistentNewlines (Just ty) = loop
  where
  loop inp0 = S.effect $ S.next inp0 >>= \case
    Left r -> pure $ pure r
    Right (nl@(L0.Eol l' ty'), rest) -> do
      when (ty /= ty') $ recoverableError $ MixedNewlines
        { errorLoc = l'
        , expectedNlType = ty
        , foundNlType = ty'
        }
      pure $ yield nl >> loop rest
    Right (other, rest) -> pure $ yield other >> loop rest

endsInNewline ::
  ( ReaderHooks m )
  => Stream (Of L0.Token) m r
  -> Stream (Of L0.Token) m r
endsInNewline inp0 = S.effect $ S.next inp0 >>= \case
-- at last token
  Right (x, inp1) -> S.next inp1 >>= \case
    Left r -> do
      case x of
        L0.Eol l Eof -> styleNote $ MissingNlAtEof l
        _ -> pure ()
      pure $ yield x >> pure r
-- not at last token
    Right (y, inp2) -> do
      let rest = yield y >> inp2
      pure $ yield x >> endsInNewline rest
  Left r -> pure $ pure r
